--- create monthly ----

CREATE TABLE "TB_DB_SQL_TIME_OUT_201801" AT "FUJIAN_MONITOR"
(
"DBUSER" VARCHAR(50),
"DBIP" VARCHAR(50),
"SQLTEXT" VARCHAR(1024),
"CPUTIMECALL" BIGINT,
"APPNAME" VARCHAR(100),
"NODEID" BIGINT,
"TIME" VARCHAR(50)) STORAGE( INITIAL 1 , NEXT 1 , MINEXTENTS 1 , on "PRIMARY", FILLFACTOR 0 ) ;



--- create daily ----
CREATE TABLE "TB_DB_LONG_SESSION_20180126" AT "FUJIAN_MONITOR"
(
"DBUSER" VARCHAR(50),
"DBIP" VARCHAR(50),
"LOGINTIME" VARCHAR(50),
"APPNAME" VARCHAR(100),
"NODEID" BIGINT,
"TIME" VARCHAR(50)) STORAGE( INITIAL 1 , NEXT 1 , MINEXTENTS 1 , on "PRIMARY", FILLFACTOR 0 ) ;